# Generated by Django 6.0.3 on 2026-04-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waybills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='waybill',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='waybill',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='waybill',
            name='loading_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='waybillitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='waybillitem',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
